default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: journey_development
  
test:
  adapter: postgresql
  encoding: unicode
  database: journey_test

production:
  adapter: postgresql
  encoding: unicode
  database: journey_production
